### PR TITLE
Adding Support Economy Money!

### PR DESCRIPTION
**Pull request by SuperKali**
started with this comment is I finish it tomorrow in the day!

### CODE REVIEW

**Comment by armagadon159753** [comment]
That look good

**Comment by SuperKali** [comment]
@armagadon159753 is good my code?

**Comment by SuperKali** [comment]
now i go at sleep, tomorrow i finish this

**Comment by SuperKali** [comment]
@xXNiceAssasinl0 why you remove my economy?

**Comment by xXNiceAssasinl0** [comment]
@SuperKali it not working do not add it please.

**Comment by SuperKali** [comment]
before i have tested and work fine, if he did not go I did not publish it, he reasons before writing @xXNiceAssasinl0

**Comment by SuperKali** [comment]
image
@xXNiceAssasinl0 working fine -.-

**Comment by xXNiceAssasinl0** [comment]
@SuperKali let me we merge

**Comment by armagadon159753** [comment]
Can i revet  this pr? And the last one

**Pull request merged**
