### PR TITLE
Add DeviceOS

### PR DESCRIPTION
**Pull request by armagadon159753**

### CODE REVIEW

**Comment by armagadon159753** [comment]
@SuperKali @xXNiceAssasinl0 @OhhhAlex @AppleNulia need review

**Comment by armagadon159753** [comment]
😕

**Comment by xXNiceAssasinl0** [comment]
No

**Comment by armagadon159753** [comment]
@SuperKali ??? Wath

**Comment by armagadon159753** [comment]
Such as your comment

**Pull request closed without merging**
